// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function Connect(arg1:db.Config):Promise<void>;

export function ConnectWithURL(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<db.QueryResult>;

export function GetColumns(arg1:string,arg2:string):Promise<Array<db.Column>>;

export function GetPrimaryKeys(arg1:string,arg2:string):Promise<Array<string>>;

export function GetSavedConnections():Promise<Array<db.SavedConnection>>;

export function GetTables():Promise<Array<db.Table>>;

export function Greet(arg1:string):Promise<string>;

export function Ping():Promise<void>;

export function SaveConnection(arg1:db.SavedConnection):Promise<db.SavedConnection>;
