// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectWithURL(arg1) {
  return window['go']['main']['App']['ConnectWithURL'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function GetColumns(arg1, arg2) {
  return window['go']['main']['App']['GetColumns'](arg1, arg2);
}

export function GetPrimaryKeys(arg1, arg2) {
  return window['go']['main']['App']['GetPrimaryKeys'](arg1, arg2);
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}
